// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heneurowlydzwmzqjraq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbmV1cm93bHlkendtenFqcmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTg1NDUsImV4cCI6MjA1NzQ3NDU0NX0.YfaZLhhZ4upaX7QJ4c4AISjDtcKTX_zM5K173qvoKyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);